services:
  app:
    build:
      context: .
      args:
        UID: ${HOST_UID:-1000}
        GID: ${HOST_GID:-1000}
    volumes:
      - .:/app:z
      - vendor:/app/vendor
      - app-var:/app/var
      - composer-cache:/tmp/composer-cache
    working_dir: /app

volumes:
  vendor:
  app-var:
  composer-cache:
